cameroon_aoi_bbx = "geojson file path"
predicted_image_asset = "google earth emgine users assets"
google_map_auth_json_data = """{
  "type": "service_account",
  "project_id": "xx",
  "private_key_id": "xx",
  "private_key": "xx",
  "client_email": "xx",
  "client_id": "xx",
  "auth_uri": "xx",
  "token_uri": "xx",
  "auth_provider_x509_cert_url": "xx",
  "client_x509_cert_url": "xx",
  "universe_domain": "xx"
}"""

[azure_blob_storage]
storage_resource_url = "your resource url"
storage_credential_token = "your token url"
